export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const ABOUT_RECIVED = 'ABOUT_RECIVED';
export const ABOUT_REQUESTED = 'ABOUT_REQUESTED';
